"""Added uniquename field to Movie.

Revision ID: c4649cdd25e7
Revises: 48e104a2b4dc
Create Date: 2019-02-28 18:25:25.813312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4649cdd25e7'
down_revision = '48e104a2b4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('uniquename', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'uniquename')
    # ### end Alembic commands ###
