"""Added UserMovie class.

Revision ID: 6a86413a888f
Revises: 341a0b928552
Create Date: 2019-04-23 10:30:34.249735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a86413a888f'
down_revision = '341a0b928552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_movie',
    sa.Column('user_movie_id', sa.Integer(), nullable=False),
    sa.Column('user_movie_name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_movie')
    # ### end Alembic commands ###
